path = r'C:\Users\giancarlo.lam\Downloads\Planes FERCO V3\index.html'
with open(path, 'rb') as f:
    content = f.read()

CRLF = b'\r\n'

# ──────────────────────────────────────────────────────────────────────────────
# BLOCK TO REPLACE: openUserModal through populateReportaA (end of that function)
# ──────────────────────────────────────────────────────────────────────────────

old_block = b'\r\n'.join([
    b"window.openUserModal=()=>{",
    b"  document.getElementById('userModalOverlay').classList.add('open');",
    b"  hideErr('userErrMsg');",
    b"  ['uNombre','uEmail','uCargo'].forEach(id=>{const el=document.getElementById(id);if(el){el.value='';if(el.dataset)el.dataset.path='';}});",
    b"  document.getElementById('uPais').value='';",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.value='';areaSel.disabled=true;",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el pa\xc3\xads primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccion').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolPuesto').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona la direcci\xc3\xb3n primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccionWrap').style.display='none';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uEsRhGlobal').checked=false;",
    b"  document.getElementById('uRhGlobalWrap').style.display=",
    b"    (userProfile?.rol==='rh'||userProfile?.esRhGlobal)?'':'none';",
    b"  populateReportaA();",
    b"};",
    b"window.closeUserModal=()=>document.getElementById('userModalOverlay').classList.remove('open');",
    b"",
    b"// Extrae lista plana {label,path} de todos los roles bajo un nodo",
    b"function flattenRoles(node,path){",
    b"  if(!path) path=[];",
    b"  const result=[];",
    b"  const hasSub='sub' in Object(node);",
    b"  const children=hasSub?node.sub:node;",
    b"  if(!children||typeof children!=='object') return result;",
    b"  for(const[key,val] of Object.entries(children)){",
    b"    const newPath=[...path,key];",
    b"    result.push({label:key,path:newPath});",
    b"    const subNode=val&&typeof val==='object'&&'sub' in val?val.sub:val;",
    b"    if(subNode&&typeof subNode==='object'&&Object.keys(subNode).length>0)",
    b"      result.push(...flattenRoles(val,newPath));",
    b"  }",
    b"  return result;",
    b"}",
    b"",
    b"// Pa\xc3\xads cambia \xe2\x86\x92 habilitar \xc3\x81rea",
    b"window.onPaisChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccion').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolPuesto').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona la direcci\xc3\xb3n primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccionWrap').style.display='none';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uCargo').value='';",
    b"  if(!pais){areaSel.disabled=true;return;}",
    b"  const areas=Object.keys(FERCO_HIERARCHY[pais]||{});",
    b"  areas.forEach(a=>{const o=document.createElement('option');o.value=a;o.textContent=a;areaSel.appendChild(o);});",
    b"  areaSel.disabled=false;",
    b"  populateReportaA();",
    b"};",
    b"",
    b"// \xc3\x81rea cambia \xe2\x86\x92 poblar Direcci\xc3\xb3n",
    b"window.onAreaChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const area=document.getElementById('uArea').value;",
    b"  const dirSel=document.getElementById('uDireccion');",
    b"  dirSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolPuesto').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona la direcci\xc3\xb3n primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccionWrap').style.display='none';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uCargo').value='';",
    b"  if(!area) return;",
    b"  const areaNode=FERCO_HIERARCHY[pais]?.[area];",
    b"  if(!areaNode) return;",
    b"  Object.keys(areaNode).forEach(dir=>{const o=document.createElement('option');o.value=dir;o.textContent=dir;dirSel.appendChild(o);});",
    b"  document.getElementById('uDireccionWrap').style.display='';",
    b"  populateReportaA();",
    b"};",
    b"",
    b"// Direcci\xc3\xb3n cambia \xe2\x86\x92 poblar Rol/Puesto con lista plana",
    b"window.onDireccionChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const area=document.getElementById('uArea').value;",
    b"  const dir=document.getElementById('uDireccion').value;",
    b"  const rolSel=document.getElementById('uRolPuesto');",
    b"  rolSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el rol \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uCargo').value='';",
    b"  if(!dir) return;",
    b"  const dirNode=FERCO_HIERARCHY[pais]?.[area]?.[dir];",
    b"  // La Direcci\xc3\xb3n es tambi\xc3\xa9n un cargo asignable",
    b"  const o0=document.createElement('option');",
    b"  o0.value=dir;o0.textContent=dir;o0.dataset.path=JSON.stringify([dir]);",
    b"  rolSel.appendChild(o0);",
    b"  // A\xc3\xb1adir todos los roles subordinados (lista plana)",
    b"  if(dirNode){",
    b"    flattenRoles(dirNode,[dir]).forEach(function(item){",
    b"      const o=document.createElement('option');",
    b"      o.value=item.label;o.textContent=item.label;",
    b"      o.dataset.path=JSON.stringify(item.path);",
    b"      rolSel.appendChild(o);",
    b"    });",
    b"  }",
    b"  document.getElementById('uRolWrap').style.display='';",
    b"  populateReportaA();",
    b"};",
    b"",
    b"// Rol/Puesto cambia \xe2\x86\x92 mostrar cargo y filtrar Reporta a",
    b"window.onRolPuestoChange=()=>{",
    b"  const rolSel=document.getElementById('uRolPuesto');",
    b"  const selected=rolSel.options[rolSel.selectedIndex];",
    b"  const cargo=rolSel.value;",
    b"  const cargoInput=document.getElementById('uCargo');",
    b"  if(!cargo){",
    b"    document.getElementById('uCargoWrap').style.display='none';",
    b"    cargoInput.value='';",
    b"    if(cargoInput.dataset) cargoInput.dataset.path='';",
    b"    populateReportaA();",
    b"    return;",
    b"  }",
    b"  cargoInput.value=cargo;",
    b"  document.getElementById('uCargoWrap').style.display='';",
    b"  const path=selected&&selected.dataset&&selected.dataset.path?JSON.parse(selected.dataset.path):[cargo];",
    b"  cargoInput.dataset.path=JSON.stringify(path);",
    b"  populateReportaA(cargo,path);",
    b"};",
    b"",
    b"// Poblar selector Reporta A, filtrado por jerarqu\xc3\xada superior al cargo",
    b"function populateReportaA(cargo,path){",
    b"  const sel=document.getElementById('uReportaA');",
    b"  sel.innerHTML='<option value=\"\">\xe2\x80\x94 Sin asignaci\xc3\xb3n \xe2\x80\x94</option>';",
    b"  const pais=document.getElementById('uPais')?.value||'';",
    b"  const area=document.getElementById('uArea')?.value||'';",
    b"  const dir=document.getElementById('uDireccion')?.value||'';",
    b"  if(!cargo||!path){",
    b"    allUsers.forEach(function(u){",
    b"      const o=document.createElement('option');",
    b"      o.value=u.uid;",
    b"      o.textContent=u.nombre+' \xe2\x80\x94 '+(u.cargo||rolLabel(u.rol)||u.rol||'\xe2\x80\x94');",
    b"      sel.appendChild(o);",
    b"    });",
    b"    return;",
    b"  }",
    b"  const superiorCargos=new Set(path.slice(0,-1));",
    b"  if(dir&&cargo!==dir) superiorCargos.add(dir);",
    b"  allUsers.forEach(function(u){",
    b"    const mismaJerarquia=u.pais===pais&&u.area===area&&superiorCargos.has(u.cargo);",
    b"    const esAdmin=['rh','rh_global','ceo','director'].includes(u.rol);",
    b"    if(!mismaJerarquia&&!esAdmin) return;",
    b"    const o=document.createElement('option');",
    b"    o.value=u.uid;",
    b"    o.textContent=u.nombre+' \xe2\x80\x94 '+(u.cargo||rolLabel(u.rol)||u.rol||'\xe2\x80\x94');",
    b"    sel.appendChild(o);",
    b"  });",
    b"}",
    b"",
]) + CRLF

new_block = b'\r\n'.join([
    b"window.openUserModal=()=>{",
    b"  document.getElementById('userModalOverlay').classList.add('open');",
    b"  hideErr('userErrMsg');",
    b"  ['uNombre','uEmail','uCargo'].forEach(id=>{const el=document.getElementById(id);if(el) el.value='';});",
    b"  document.getElementById('uPais').value='';",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.value='';areaSel.disabled=true;",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el pa\xc3\xads primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uEsRhGlobal').checked=false;",
    b"  document.getElementById('uRhGlobalWrap').style.display=",
    b"    (userProfile?.rol==='rh'||userProfile?.esRhGlobal)?'':'none';",
    b"  populateReportaA();",
    b"};",
    b"window.closeUserModal=()=>document.getElementById('userModalOverlay').classList.remove('open');",
    b"",
    b"// Pa\xc3\xads cambia \xe2\x86\x92 habilitar \xc3\x81rea",
    b"window.onPaisChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea \xe2\x80\x94</option>';",
    b"  if(!pais){areaSel.disabled=true;return;}",
    b"  const areas=Object.keys(FERCO_HIERARCHY[pais]||{});",
    b"  areas.forEach(a=>{const o=document.createElement('option');o.value=a;o.textContent=a;areaSel.appendChild(o);});",
    b"  areaSel.disabled=false;",
    b"};",
    b"",
    b"// Poblar Reporta A con TODOS los usuarios",
    b"function populateReportaA(){",
    b"  const sel=document.getElementById('uReportaA');",
    b"  sel.innerHTML='<option value=\"\">\xe2\x80\x94 Sin asignaci\xc3\xb3n \xe2\x80\x94</option>';",
    b"  allUsers.forEach(function(u){",
    b"    const o=document.createElement('option');",
    b"    o.value=u.uid;",
    b"    o.textContent=u.nombre+' \xe2\x80\x94 '+(u.cargo||rolLabel(u.rol)||u.rol||'\xe2\x80\x94');",
    b"    sel.appendChild(o);",
    b"  });",
    b"}",
    b"",
]) + CRLF

print('Found old block:', old_block in content)
content = content.replace(old_block, new_block)
with open(path, 'wb') as f:
    f.write(content)
print('JS functions done.')
