path = r'C:\Users\giancarlo.lam\Downloads\Planes FERCO V3\index.html'
with open(path, 'rb') as f:
    content = f.read()

CRLF = b'\r\n'

# The old saveUser variable-reading + validation block
old_vars = (
    b"window.saveUser=async()=>{\r\n"
    b"  const nombre=document.getElementById('uNombre').value.trim();\r\n"
    b"  const email=document.getElementById('uEmail').value.trim();\r\n"
    b"  const pais=document.getElementById('uPais')?.value||'';\r\n"
    b"  const area=document.getElementById('uArea')?.value||'';\r\n"
    b"  const cargo=document.getElementById('uCargo')?.value||'';\r\n"
    b"  const esRhGlobal=document.getElementById('uEsRhGlobal')?.checked||false;\r\n"
    b"  const reportaA=document.getElementById('uReportaA')?.value||'';\r\n"
    b"\r\n"
    b"  // Recopilar path jer\xc3\xa1rquico (niveles 3-8)\r\n"
    b"  const jerarquia={};\r\n"
    b"  for(let n=3;n<=8;n++){\r\n"
    b"    const v=document.getElementById(`uNivel${n}`)?.value;\r\n"
    b"    if(v) jerarquia[`nivel${n}`]=v;\r\n"
    b"  }\r\n"
    b"  const nivel3=jerarquia.nivel3||'';\r\n"
    b"\r\n"
    b"  // Validaciones\r\n"
    b"  if(!nombre||!email){showErr('userErrMsg','Completa el nombre y correo del usuario.');return;}\r\n"
    b"  if(!pais||!area){showErr('userErrMsg','Selecciona el pa\xc3\xads y el \xc3\xa1rea.');return;}\r\n"
    b"  if(!cargo){showErr('userErrMsg','Selecciona el cargo en la jerarqu\xc3\xada.');return;}\r\n"
    b"\r\n"
    b"  // Derivar rol legacy para compatibilidad con acceso control\r\n"
    b"  const rolLegacy=esRhGlobal?'rh':deriveRolLegacy(cargo,area,nivel3);\r\n"
    b"\r\n"
    b"  // Generar contrase\xc3\xb1a aleatoria de 16 caracteres\r\n"
    b"  const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';\r\n"
    b"  let pass='';\r\n"
    b"  for(let i=0;i<16;i++) pass+=chars.charAt(Math.floor(Math.random()*chars.length));\r\n"
    b"\r\n"
    b"  try{\r\n"
    b"    const secondaryApp=initializeApp(firebaseConfig,'secondary_'+Date.now());\r\n"
    b"    const secondaryAuth=getAuth(secondaryApp);\r\n"
    b"    const cred=await createUserWithEmailAndPassword(secondaryAuth,email,pass);\r\n"
    b"    const uid=cred.user.uid;\r\n"
    b"    await sendPasswordResetEmail(secondaryAuth,email);\r\n"
    b"    await signOut(secondaryAuth);\r\n"
    b"    await deleteApp(secondaryApp);\r\n"
    b"\r\n"
    b"    const profile={\r\n"
    b"      nombre,email,\r\n"
    b"      cargo,\r\n"
    b"      area:esRhGlobal?'rh_global':area,\r\n"
    b"      ...jerarquia,\r\n"
    b"      pais:esRhGlobal?'Global':(pais||''),\r\n"
    b"      esRhGlobal,\r\n"
    b"      rol:rolLegacy,\r\n"
    b"      reportaA\r\n"
    b"    };\r\n"
)

new_vars = (
    b"window.saveUser=async()=>{\r\n"
    b"  const nombre=document.getElementById('uNombre').value.trim();\r\n"
    b"  const email=document.getElementById('uEmail').value.trim();\r\n"
    b"  const pais=document.getElementById('uPais')?.value||'';\r\n"
    b"  const area=document.getElementById('uArea')?.value||'';\r\n"
    b"  const dir=document.getElementById('uDireccion')?.value||'';\r\n"
    b"  const cargo=document.getElementById('uCargo')?.value||'';\r\n"
    b"  const esRhGlobal=document.getElementById('uEsRhGlobal')?.checked||false;\r\n"
    b"  const reportaA=document.getElementById('uReportaA')?.value||'';\r\n"
    b"\r\n"
    b"  // Leer path jer\xc3\xa1rquico desde dataset del input de cargo\r\n"
    b"  const pathRaw=document.getElementById('uCargo')?.dataset?.path;\r\n"
    b"  const rolPath=pathRaw?JSON.parse(pathRaw):(cargo?[cargo]:[]);\r\n"
    b"  // Guardar nivel3..nivelN (nivel3 siempre es la Direcci\xc3\xb3n)\r\n"
    b"  const jerarquia={};\r\n"
    b"  rolPath.forEach(function(v,i){jerarquia['nivel'+(i+3)]=v;});\r\n"
    b"  if(dir&&!jerarquia.nivel3) jerarquia.nivel3=dir;\r\n"
    b"  const nivel3=dir;\r\n"
    b"\r\n"
    b"  // Validaciones\r\n"
    b"  if(!nombre||!email){showErr('userErrMsg','Completa el nombre y correo del usuario.');return;}\r\n"
    b"  if(!pais||!area){showErr('userErrMsg','Selecciona el pa\xc3\xads y el \xc3\xa1rea.');return;}\r\n"
    b"  if(!dir){showErr('userErrMsg','Selecciona la direcci\xc3\xb3n.');return;}\r\n"
    b"  if(!cargo){showErr('userErrMsg','Selecciona el rol o puesto.');return;}\r\n"
    b"\r\n"
    b"  // Derivar rol legacy para compatibilidad con acceso control\r\n"
    b"  const rolLegacy=esRhGlobal?'rh':deriveRolLegacy(cargo,area,nivel3);\r\n"
    b"\r\n"
    b"  // Generar contrase\xc3\xb1a aleatoria de 16 caracteres\r\n"
    b"  const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';\r\n"
    b"  let pass='';\r\n"
    b"  for(let i=0;i<16;i++) pass+=chars.charAt(Math.floor(Math.random()*chars.length));\r\n"
    b"\r\n"
    b"  try{\r\n"
    b"    const secondaryApp=initializeApp(firebaseConfig,'secondary_'+Date.now());\r\n"
    b"    const secondaryAuth=getAuth(secondaryApp);\r\n"
    b"    const cred=await createUserWithEmailAndPassword(secondaryAuth,email,pass);\r\n"
    b"    const uid=cred.user.uid;\r\n"
    b"    await sendPasswordResetEmail(secondaryAuth,email);\r\n"
    b"    await signOut(secondaryAuth);\r\n"
    b"    await deleteApp(secondaryApp);\r\n"
    b"\r\n"
    b"    const profile={\r\n"
    b"      nombre,email,\r\n"
    b"      cargo,\r\n"
    b"      direccion:dir,\r\n"
    b"      area:esRhGlobal?'rh_global':area,\r\n"
    b"      ...jerarquia,\r\n"
    b"      pais:esRhGlobal?'Global':(pais||''),\r\n"
    b"      esRhGlobal,\r\n"
    b"      rol:rolLegacy,\r\n"
    b"      reportaA\r\n"
    b"    };\r\n"
)

print('Found old_vars:', old_vars in content)
content = content.replace(old_vars, new_vars)
with open(path, 'wb') as f:
    f.write(content)
print('Done.')
