import sys

path = r'C:\Users\giancarlo.lam\Downloads\Planes FERCO V3\index.html'
with open(path, 'rb') as f:
    content = f.read()

CRLF = b'\r\n'

def L(s):
    return s.encode('utf-8') + CRLF

old_lines = [
    b"window.openUserModal=()=>{",
    b"  document.getElementById('userModalOverlay').classList.add('open');",
    b"  hideErr('userErrMsg');",
    b"  // Limpiar campos b\xc3\xa1sicos",
    b"  ['uNombre','uEmail','uCargo'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});",
    b"  // Resetear Pa\xc3\xads y \xc3\x81rea",
    b"  document.getElementById('uPais').value='';",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.value='';",
    b"  areaSel.disabled=true;",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el pa\xc3\xads primero \xe2\x80\x94</option>';",
    b"  // Limpiar niveles din\xc3\xa1micos y cargo",
    b"  document.getElementById('uNivelRows').innerHTML='';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uEsRhGlobal').checked=false;",
    b"  // Mostrar checkbox RH Global solo a usuarios rh / esRhGlobal",
    b"  document.getElementById('uRhGlobalWrap').style.display=",
    b"    (userProfile?.rol==='rh'||userProfile?.esRhGlobal)?'':'none';",
    b"  populateReportaA();",
    b"};",
    b"window.closeUserModal=()=>document.getElementById('userModalOverlay').classList.remove('open');",
    b"",
    b"// Poblar el selector Reporta A",
    b"function populateReportaA(){",
    b"  const sel=document.getElementById('uReportaA');",
    b"  sel.innerHTML='<option value=\"\">\xe2\x80\x94 Sin asignaci\xc3\xb3n \xe2\x80\x94</option>';",
    b"  allUsers.forEach(u=>{",
    b"    const o=document.createElement('option');",
    b"    o.value=u.uid;",
    b"    o.textContent=`${u.nombre} (${u.cargo||rolLabel(u.rol)||u.rol||'\xe2\x80\x94'})`;",
    b"    sel.appendChild(o);",
    b"  });",
    b"}",
    b"",
    b"// Manejo de cambio en cualquier nivel de jerarqu\xc3\xada (arranca en nivel 3)",
    b"window.onNivelChange=(nivel)=>{",
    b"  // Eliminar niveles posteriores",
    b"  for(let n=nivel+1;n<=8;n++){",
    b"    const el=document.getElementById(`uNivel${n}Row`);if(el)el.remove();",
    b"  }",
    b"  updateCargoBadge();",
    b"  // Navegar por el \xc3\xa1rbol: Pa\xc3\xads \xe2\x86\x92 \xc3\x81rea \xe2\x86\x92 nivel3\xe2\x80\xa6nivelN",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const area=document.getElementById('uArea').value;",
    b"  let node=FERCO_HIERARCHY[pais]?.[area];",
    b"  for(let n=3;n<=nivel;n++){",
    b"    const val=document.getElementById(`uNivel${n}`)?.value;",
    b"    if(!val) return;",
    b"    node=node?.[val]?.sub||node?.[val];",
    b"    if(!node) return;",
    b"  }",
    b"  // Renderizar siguiente nivel si hay hijos",
    b"  const children=node?.sub||(typeof node==='object'&&!node.sub?node:null);",
    b"  if(children&&Object.keys(children).length>0) renderNivelRow(nivel+1,children);",
    b"  updateCargoBadge();",
    b"};",
    b"",
    b"function updateCargoBadge(){",
    b"  let cargo='';",
    b"  for(let n=8;n>=3;n--){",
    b"    const v=document.getElementById(`uNivel${n}`)?.value;",
    b"    if(v){cargo=v;break;}",
    b"  }",
    b"  const wrap=document.getElementById('uCargoWrap');",
    b"  if(cargo){document.getElementById('uCargo').value=cargo;wrap.style.display='';}",
    b"  else wrap.style.display='none';",
    b"}",
    b"",
    b"function renderNivelRow(nivel,nodeOrSub){",
    b"  const children=nodeOrSub?.sub||nodeOrSub;",
    b"  if(!children||Object.keys(children).length===0) return;",
    b"  const row=document.createElement('div');",
    b"  row.id=`uNivel${nivel}Row`;",
    b"  row.className='form-group';",
    b"  row.innerHTML=`<label>Nivel ${nivel}</label>",
    b"    <select id=\"uNivel${nivel}\" onchange=\"onNivelChange(${nivel})\">",
    b"      <option value=\"\">\xe2\x80\x94 Selecciona \xe2\x80\x94</option>",
    b"      ${Object.keys(children).map(k=>`<option value=\"${escHtml(k)}\">${escHtml(k)}</option>`).join('')}",
    b"    </select>`;",
    b"  document.getElementById('uNivelRows').appendChild(row);",
    b"}",
    b"",
    b"window.onPaisChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea \xe2\x80\x94</option>';",
    b"  document.getElementById('uNivelRows').innerHTML='';",
    b"  updateCargoBadge();",
    b"  if(!pais){areaSel.disabled=true;return;}",
    b"  const areas=Object.keys(FERCO_HIERARCHY[pais]||{});",
    b"  areas.forEach(a=>{const o=document.createElement('option');o.value=a;o.textContent=a;areaSel.appendChild(o);});",
    b"  areaSel.disabled=false;",
    b"};",
    b"",
    b"window.onAreaChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const area=document.getElementById('uArea').value;",
    b"  document.getElementById('uNivelRows').innerHTML='';",
    b"  updateCargoBadge();",
    b"  if(!area) return;",
    b"  const node=FERCO_HIERARCHY[pais]?.[area];",
    b"  if(!node) return;",
    b"  renderNivelRow(3,node);",
    b"};",
    b"",
]

new_lines = [
    b"window.openUserModal=()=>{",
    b"  document.getElementById('userModalOverlay').classList.add('open');",
    b"  hideErr('userErrMsg');",
    b"  ['uNombre','uEmail','uCargo'].forEach(id=>{const el=document.getElementById(id);if(el){el.value='';if(el.dataset)el.dataset.path='';}});",
    b"  document.getElementById('uPais').value='';",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.value='';areaSel.disabled=true;",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el pa\xc3\xads primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccion').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolPuesto').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona la direcci\xc3\xb3n primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccionWrap').style.display='none';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uEsRhGlobal').checked=false;",
    b"  document.getElementById('uRhGlobalWrap').style.display=",
    b"    (userProfile?.rol==='rh'||userProfile?.esRhGlobal)?'':'none';",
    b"  populateReportaA();",
    b"};",
    b"window.closeUserModal=()=>document.getElementById('userModalOverlay').classList.remove('open');",
    b"",
    b"// Extrae lista plana {label,path} de todos los roles bajo un nodo",
    b"function flattenRoles(node,path){",
    b"  if(!path) path=[];",
    b"  const result=[];",
    b"  const hasSub='sub' in Object(node);",
    b"  const children=hasSub?node.sub:node;",
    b"  if(!children||typeof children!=='object') return result;",
    b"  for(const[key,val] of Object.entries(children)){",
    b"    const newPath=[...path,key];",
    b"    result.push({label:key,path:newPath});",
    b"    const subNode=val&&typeof val==='object'&&'sub' in val?val.sub:val;",
    b"    if(subNode&&typeof subNode==='object'&&Object.keys(subNode).length>0)",
    b"      result.push(...flattenRoles(val,newPath));",
    b"  }",
    b"  return result;",
    b"}",
    b"",
    b"// Pa\xc3\xads cambia \xe2\x86\x92 habilitar \xc3\x81rea",
    b"window.onPaisChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const areaSel=document.getElementById('uArea');",
    b"  areaSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccion').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el \xc3\xa1rea primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolPuesto').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona la direcci\xc3\xb3n primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccionWrap').style.display='none';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uCargo').value='';",
    b"  if(!pais){areaSel.disabled=true;return;}",
    b"  const areas=Object.keys(FERCO_HIERARCHY[pais]||{});",
    b"  areas.forEach(a=>{const o=document.createElement('option');o.value=a;o.textContent=a;areaSel.appendChild(o);});",
    b"  areaSel.disabled=false;",
    b"  populateReportaA();",
    b"};",
    b"",
    b"// \xc3\x81rea cambia \xe2\x86\x92 poblar Direcci\xc3\xb3n",
    b"window.onAreaChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const area=document.getElementById('uArea').value;",
    b"  const dirSel=document.getElementById('uDireccion');",
    b"  dirSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolPuesto').innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona la direcci\xc3\xb3n primero \xe2\x80\x94</option>';",
    b"  document.getElementById('uDireccionWrap').style.display='none';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uCargo').value='';",
    b"  if(!area) return;",
    b"  const areaNode=FERCO_HIERARCHY[pais]?.[area];",
    b"  if(!areaNode) return;",
    b"  Object.keys(areaNode).forEach(dir=>{const o=document.createElement('option');o.value=dir;o.textContent=dir;dirSel.appendChild(o);});",
    b"  document.getElementById('uDireccionWrap').style.display='';",
    b"  populateReportaA();",
    b"};",
    b"",
    b"// Direcci\xc3\xb3n cambia \xe2\x86\x92 poblar Rol/Puesto con lista plana",
    b"window.onDireccionChange=()=>{",
    b"  const pais=document.getElementById('uPais').value;",
    b"  const area=document.getElementById('uArea').value;",
    b"  const dir=document.getElementById('uDireccion').value;",
    b"  const rolSel=document.getElementById('uRolPuesto');",
    b"  rolSel.innerHTML='<option value=\"\">\xe2\x80\x94 Selecciona el rol \xe2\x80\x94</option>';",
    b"  document.getElementById('uRolWrap').style.display='none';",
    b"  document.getElementById('uCargoWrap').style.display='none';",
    b"  document.getElementById('uCargo').value='';",
    b"  if(!dir) return;",
    b"  const dirNode=FERCO_HIERARCHY[pais]?.[area]?.[dir];",
    b"  // La Direcci\xc3\xb3n es tambi\xc3\xa9n un cargo asignable",
    b"  const o0=document.createElement('option');",
    b"  o0.value=dir;o0.textContent=dir;o0.dataset.path=JSON.stringify([dir]);",
    b"  rolSel.appendChild(o0);",
    b"  // A\xc3\xb1adir todos los roles subordinados (lista plana)",
    b"  if(dirNode){",
    b"    flattenRoles(dirNode,[dir]).forEach(function(item){",
    b"      const o=document.createElement('option');",
    b"      o.value=item.label;o.textContent=item.label;",
    b"      o.dataset.path=JSON.stringify(item.path);",
    b"      rolSel.appendChild(o);",
    b"    });",
    b"  }",
    b"  document.getElementById('uRolWrap').style.display='';",
    b"  populateReportaA();",
    b"};",
    b"",
    b"// Rol/Puesto cambia \xe2\x86\x92 mostrar cargo y filtrar Reporta a",
    b"window.onRolPuestoChange=()=>{",
    b"  const rolSel=document.getElementById('uRolPuesto');",
    b"  const selected=rolSel.options[rolSel.selectedIndex];",
    b"  const cargo=rolSel.value;",
    b"  const cargoInput=document.getElementById('uCargo');",
    b"  if(!cargo){",
    b"    document.getElementById('uCargoWrap').style.display='none';",
    b"    cargoInput.value='';",
    b"    if(cargoInput.dataset) cargoInput.dataset.path='';",
    b"    populateReportaA();",
    b"    return;",
    b"  }",
    b"  cargoInput.value=cargo;",
    b"  document.getElementById('uCargoWrap').style.display='';",
    b"  const path=selected&&selected.dataset&&selected.dataset.path?JSON.parse(selected.dataset.path):[cargo];",
    b"  cargoInput.dataset.path=JSON.stringify(path);",
    b"  populateReportaA(cargo,path);",
    b"};",
    b"",
    b"// Poblar selector Reporta A, filtrado por jerarqu\xc3\xada superior al cargo",
    b"function populateReportaA(cargo,path){",
    b"  const sel=document.getElementById('uReportaA');",
    b"  sel.innerHTML='<option value=\"\">\xe2\x80\x94 Sin asignaci\xc3\xb3n \xe2\x80\x94</option>';",
    b"  const pais=document.getElementById('uPais')?.value||'';",
    b"  const area=document.getElementById('uArea')?.value||'';",
    b"  const dir=document.getElementById('uDireccion')?.value||'';",
    b"  if(!cargo||!path){",
    b"    allUsers.forEach(function(u){",
    b"      const o=document.createElement('option');",
    b"      o.value=u.uid;",
    b"      o.textContent=u.nombre+' \xe2\x80\x94 '+(u.cargo||rolLabel(u.rol)||u.rol||'\xe2\x80\x94');",
    b"      sel.appendChild(o);",
    b"    });",
    b"    return;",
    b"  }",
    b"  const superiorCargos=new Set(path.slice(0,-1));",
    b"  if(dir&&cargo!==dir) superiorCargos.add(dir);",
    b"  allUsers.forEach(function(u){",
    b"    const mismaJerarquia=u.pais===pais&&u.area===area&&superiorCargos.has(u.cargo);",
    b"    const esAdmin=['rh','rh_global','ceo','director'].includes(u.rol);",
    b"    if(!mismaJerarquia&&!esAdmin) return;",
    b"    const o=document.createElement('option');",
    b"    o.value=u.uid;",
    b"    o.textContent=u.nombre+' \xe2\x80\x94 '+(u.cargo||rolLabel(u.rol)||u.rol||'\xe2\x80\x94');",
    b"    sel.appendChild(o);",
    b"  });",
    b"}",
    b"",
]

old_block = CRLF.join(old_lines)
new_block = CRLF.join(new_lines)

print('Found:', old_block in content)
content = content.replace(old_block, new_block)
with open(path, 'wb') as f:
    f.write(content)
print('Done.')
